"""English long-form entries for the first Surf Japan glossary articles."""

ARTICLES = {
    "surf": {
        "standfirst": "Surf is not the energy travelling across the ocean. It is that energy at the moment the coast makes it rideable.",
        "sections": [
            ("Where surf begins", "A swell can travel in deep water for days without offering anything to stand on. As it reaches shallow water, the seabed slows its base, steepens the face and eventually makes the crest fall forward. That broken, shoreward-moving wave is surf."),
            ("Why the distinction helps", "Forecasts usually describe swell offshore. A surf report describes the breaking waves at a spot. The two are connected, but a sandbar, tide, wind and coastline can turn the same swell into clean surf at one beach and a weak closeout a few kilometres away."),
        ],
        "related": ("swell", "wave-period", "swell-direction", "surf-height"),
    },
    "swell": {
        "standfirst": "Swell is organised wave energy that has outlived the wind that made it.",
        "sections": [
            ("A traveller, not a local disturbance", "Wind first makes a confused sea. Once waves leave the storm area, the longer and more regular parts of that energy sort themselves into broad, spaced lines. Those lines can cross an ocean and arrive at a coast as swell, even when the local air is calm."),
            ("Reading a swell", "Height says how large the offshore waves are; period says how widely their energy is spaced; direction says which coastlines and headlands can receive them. Read those three together before deciding what a particular beach will do."),
        ],
        "related": ("groundswell", "wind-swell", "fetch", "wave-period", "swell-direction"),
    },
    "groundswell": {
        "standfirst": "Groundswell is a longer-period swell generated by a distant storm — usually cleaner, more organised and more powerful than nearby wind waves.",
        "sections": [
            ("Distance gives it time", "A distant storm has a long stretch of open water and time to build waves. During the journey, shorter and less organised waves fade first. What arrives is commonly a more regular pulse with a longer period."),
            ("At the coast", "Long-period energy feels the bottom farther offshore and can bend around headlands into protected bays. It may also make a familiar sandbar break farther outside and with more force than the raw height alone suggests."),
        ],
        "related": ("swell", "wind-swell", "wave-period", "fetch"),
    },
    "wind-swell": {
        "standfirst": "Wind swell is the shorter-period, locally generated end of the spectrum: often available, often changeable and strongly shaped by the weather overhead.",
        "sections": [
            ("Made close by", "When wind blows over nearby water, it transfers energy directly into the surface. If the fetch is short or the wind has only been blowing for a few hours, the resulting waves stay tightly spaced and irregular."),
            ("What to expect", "Wind swell can create fun, rideable surf, especially at exposed beach breaks. It usually has less time to organise than groundswell, so local wind matters more: a light offshore can groom it; an onshore can turn it into chop quickly."),
        ],
        "related": ("swell", "groundswell", "fetch", "wave-period"),
    },
    "fetch": {
        "standfirst": "Fetch is the length of open water over which wind blows while building waves.",
        "sections": [
            ("The runway for wind", "Given enough wind speed and time, a longer fetch lets the wind push on the sea for longer. That generally allows larger, longer-period waves to develop. A short fetch limits how much energy can build before the wind meets land or changes direction."),
            ("One part of the story", "Fetch never works alone. Wind strength, how long it lasts and how steadily it blows all matter. In a forecast, fetch helps explain why one storm produces a small local wind swell while another sends a long-period groundswell across the Pacific."),
        ],
        "related": ("wind-swell", "groundswell", "swell", "wave-period"),
    },
    "wave-period": {
        "standfirst": "Wave period is the number of seconds between crests. It is the quickest way to understand how a swell will feel, not just how tall it looks.",
        "sections": [
            ("Spacing carries information", "A six-second wave train has closely spaced crests and is commonly linked to local wind swell. A fourteen-second train has much more distance between crests and usually comes from farther away. Longer periods carry their energy deeper and interact with the coast sooner."),
            ("Use it before wave height", "Two forecasts can show the same height yet produce very different surf. The longer-period swell can arrive with more power, wrap around a headland and stand up farther outside. Treat height as one part of the forecast; use period to give it context."),
        ],
        "diagram": "period",
        "related": ("swell", "groundswell", "wind-swell", "wave-energy"),
    },
    "swell-direction": {
        "standfirst": "Swell direction is the compass direction a swell comes from. It decides whether a coast is exposed, sheltered or only catching a refracted edge.",
        "sections": [
            ("A spot has a window", "Every surf spot faces a limited arc of open ocean. A beach open to the east may receive an easterly swell directly but miss one from the west. Headlands, islands and bays narrow or bend that window further."),
            ("Direction changes the shape", "The angle of arrival also changes where energy reaches a sandbar or reef first. A small change in direction can move the peak, make one side of a break work better or turn an expected wave into a closeout."),
        ],
        "related": ("swell", "wave-period", "swell-height", "headland"),
    },
    "set": {
        "standfirst": "A set is a group of waves arriving close together, often with larger waves than the ones between.",
        "sections": [
            ("Why waves arrive in groups", "A swell is made of many overlapping wave trains. At some moments their crests line up and reinforce one another; at others they partly cancel. The visible result at a break is a pulse of larger waves followed by a quieter gap."),
            ("How to use a set", "Watch a few cycles before paddling out. Sets show where the outside peak really breaks, where the channel stops being safe and how much time remains before the next push of whitewater. Waiting for the right set is often better than chasing every small wave."),
        ],
        "related": ("lull", "swell", "wave-period", "cleanup-set"),
    },
    "lull": {
        "standfirst": "A lull is the quieter space between sets — useful for reaching the line-up, but never a promise that the ocean has gone calm.",
        "sections": [
            ("A pause in the pulse", "Between groups of waves, fewer crests arrive at once and the break can look deceptively gentle. The lull comes from the same overlapping wave energy that makes sets, not from a change in the weather."),
            ("Choose the moment", "A lull can be the best time to paddle through the impact zone or reset your position. Before committing, keep looking outside: the next set may already be visible on the horizon, and the largest waves can arrive after the longest wait."),
        ],
        "related": ("set", "paddle-out", "impact-zone", "cleanup-set"),
    },
    "paddle-out": {
        "standfirst": "Paddling out is the route and work of getting from shore to the lineup without putting yourself or others in the path of breaking waves.",
        "sections": [
            ("Find the quieter route", "Before entering the water, watch several sets. A channel, a deeper patch or the edge of the breaking area can offer a calmer way out. The safest route changes with the tide, swell and crowd, so do not assume yesterday's path still works."),
            ("Make room for riders", "Paddle wide of the peak and avoid crossing the path of someone already riding a wave. If a set arrives, protect your board and choose the option that keeps it under control. Reaching the lineup is not a race; good timing saves energy and reduces risk."),
        ],
        "related": ("lineup", "channel", "impact-zone", "caught-inside", "set"),
    },
    "caught-inside": {
        "standfirst": "Caught inside means being trapped between shore and the main breaking area, unable to reach the outside before more waves arrive.",
        "sections": [
            ("Why it happens", "A set can close the route you used on the way out, or the current can carry you into the impact zone. It is common, especially at beach breaks whose peaks and channels move. Recognising the situation early gives you more choices."),
            ("Reset safely", "Do not fight every wave in a panic. Keep control of your board, look for a gap or channel, and move away from surfers riding toward shore. If you are tiring or conditions are beyond your level, returning to the beach to reset is a sound decision."),
        ],
        "related": ("paddle-out", "inside", "outside", "impact-zone", "channel"),
    },
}
